# pytest.ini
[pytest]
# AAA: Auto-apply these flags to every single pytest run
addopts =
    -n 3
    --browser chromium
    --html=reports/automation_report.html
    --self-contained-html
    --tracing=retain-on-failure
    --screenshot=only-on-failure
    --video=retain-on-failure
    # Removed --headed. Parallel scaling requires headless execution.

markers =
    test_data_validation: Marks tests used for database negative-data validation.

# Clean up console output
console_output_style = count